@startuml
!theme sunlust
skinparam classAttributeIconSize 0

class Client {
}

interface Target {
    + request() : string
}

class Adapter {
    - adaptee: Adaptee*
    + request() : string
}

class Adaptee {
    + specificRequest() : string
}

Client ..> Target
Target <|.. Adapter
Adapter o--> Adaptee : adaptee

note right of Adapter::request
    return adaptee->specificRequest()
    with translation
end note

@enduml