@startuml
!theme sunlust
skinparam classAttributeIconSize 0

class Client {
}

interface Target {
    + request() : string
}

class ClassAdapter {
    + request() : string
}

class Adaptee {
    + specificRequest() : string
}

Client ..> Target
Target <|.. ClassAdapter
Adaptee <|-- ClassAdapter

note right of ClassAdapter::request
    return specificRequest()
    with translation
end note

@enduml