@startuml
!theme sunlust
skinparam classAttributeIconSize 0

class Client {
}

abstract class Abstraction {
    # implementation: Implementation*
    + operation(): string
}

class RefinedAbstraction {
    + operation(): string
}

interface Implementation {
    + operationImplementation(): string
}

class ConcreteImplementationA {
    + operationImplementation(): string
}

class ConcreteImplementationB {
    + operationImplementation(): string
}

Client --> Abstraction
Abstraction o--> Implementation : implementation
Abstraction <|-- RefinedAbstraction
Implementation <|.. ConcreteImplementationA
Implementation <|.. ConcreteImplementationB

note right of Abstraction::operation
    return implementation->
        operationImplementation()
end note

@enduml