@startuml
!theme sunlust
skinparam classAttributeIconSize 0

class Client {
}

class Facade {
    - subsystemA: SubsystemA*
    - subsystemB: SubsystemB*
    - subsystemC: SubsystemC*
    + operation(): void
}

class SubsystemA {
    + operationA1(): string
    + operationA2(): string
}

class SubsystemB {
    + operationB1(): string
    + operationB2(): string
}

class SubsystemC {
    + operationC1(): string
    + operationC2(): string
}

Client --> Facade
Facade --> SubsystemA
Facade --> SubsystemB
Facade --> SubsystemC

note right of Facade::operation
    subsystemA->operationA1()
    subsystemB->operationB1()
    subsystemC->operationC1()
    subsystemA->operationA2()
    subsystemB->operationB2()
    subsystemC->operationC2()
end note

@enduml