@startuml
!theme sunlust
skinparam classAttributeIconSize 0

class Client {
}

abstract class Handler {
    # nextHandler: Handler*
    + setNext(Handler*): Handler*
    + handle(request): string
}

class ConcreteHandlerA {
    + handle(request): string
}

class ConcreteHandlerB {
    + handle(request): string
}

class ConcreteHandlerC {
    + handle(request): string
}

Client --> Handler
Handler <|-- ConcreteHandlerA
Handler <|-- ConcreteHandlerB
Handler <|-- ConcreteHandlerC
Handler o--> Handler : nextHandler

note right of Handler::handle
    if (canHandle(request))
        process request
    else if (nextHandler != null)
        nextHandler->handle(request)
end note

@enduml