@startuml
!theme sunlust
interface Command {
    + execute(): void
    + undo(): void
}

class ConcreteCommand {
    - receiver: Receiver
    - parameters: Data
    + execute(): void
    + undo(): void
}

class Receiver {
    + action(): void
}

class Invoker {
    - command: Command
    + setCommand(command: Command): void
    + executeCommand(): void
}

class Client

Client --> ConcreteCommand : creates
ConcreteCommand ..|> Command
ConcreteCommand o-> Receiver
Invoker o-> Command
Client --> Receiver : creates
Client --> Invoker : creates

note right of ConcreteCommand
    command->execute() calls
    receiver->action()
end note

note right of Invoker
    Asks the command to
    carry out the request
end note
@enduml