@startuml
!theme sunlust
actor Client
participant "subject:\nConcreteSubject" as Subject
participant "observer1:\nConcreteObserver" as Observer1
participant "observer2:\nConcreteObserver" as Observer2

Client -> Subject: attach(observer1)
Client -> Subject: attach(observer2)
Client -> Subject: setState(newState)
activate Subject
Subject -> Subject: state = newState
Subject -> Subject: notify()
Subject -> Observer1: update()
activate Observer1
Observer1 -> Subject: getState()
Subject --> Observer1: newState
Observer1 -> Observer1: observerState = newState
deactivate Observer1
Subject -> Observer2: update()
activate Observer2
Observer2 -> Subject: getState()
Subject --> Observer2: newState
Observer2 -> Observer2: observerState = newState
deactivate Observer2
deactivate Subject
@enduml