@startuml
!theme sunlust
interface Subject {
    +attach(Observer): void
    +detach(Observer): void
    +notify(): void
}

interface Observer {
    +update(Subject): void
}

class ConcreteSubject {
    -state: State
    -observers: List<Observer>
    +attach(Observer): void
    +detach(Observer): void
    +notify(): void
    +getState(): State
    +setState(State): void
}

class ConcreteObserver {
    -subject: ConcreteSubject
    -observerState: State
    +update(Subject): void
}

Subject <|.. ConcreteSubject
Observer <|.. ConcreteObserver
ConcreteSubject o--> Observer : observers
ConcreteObserver --> ConcreteSubject : subject
@enduml