@startuml
!theme sunlust
class Stock {
    -symbol: string
    -price: double
    -observers: List<Investor>
    +attach(Investor): void
    +detach(Investor): void
    +notify(): void
    +setPrice(double): void
    +getSymbol(): string
    +getPrice(): double
}

class Investor {
    -name: string
    +update(Stock*): void
    +getName(): string
}

Stock o--> Investor : observers
Investor --> Stock : stocks
@enduml