@startuml
!theme sunlust
actor User
participant "context:\nContext" as Context
participant "stateA:\nConcreteStateA" as StateA
participant "stateB:\nConcreteStateB" as StateB

User -> Context: request()
activate Context
Context -> StateA: handle(context)
activate StateA
StateA -> StateA: perform action
StateA -> Context: setState(stateB)
Context -> Context: state = stateB
deactivate StateA
deactivate Context

User -> Context: request()
activate Context
Context -> StateB: handle(context)
activate StateB
StateB -> StateB: perform different action
StateB -> Context: setState(stateA)
Context -> Context: state = stateA
deactivate StateB
deactivate Context
@enduml