@startuml
!theme sunlust

[*] --> Closed
Closed --> Opening
Opening --> Open
Open --> Closing
Closing --> Closed

state Open {
  [*] --> Normal
  Normal --> Minimized
  Minimized --> Maximized
  Maximized --> Normal
  Normal --> Maximized
  Minimized --> Normal
}

@enduml
