@startuml
!theme sunlust

' Abstract interfaces
abstract class AbstractFactory {
    + {abstract} createProductA() : AbstractProductA*
    + {abstract} createProductB() : AbstractProductB*
}

abstract class AbstractProductA {
    + {abstract} usefulFunctionA() : string
}

abstract class AbstractProductB {
    + {abstract} usefulFunctionB() : string
    + {abstract} anotherUsefulFunctionB(AbstractProductA&) : string
}

' Family 1 - Concrete implementations
package "Product Family 1" {
    class ConcreteFactory1 {
        + createProductA() : AbstractProductA*
        + createProductB() : AbstractProductB*
    }
    
    class ConcreteProductA1 {
        + usefulFunctionA() : string
    }
    
    class ConcreteProductB1 {
        + usefulFunctionB() : string
        + anotherUsefulFunctionB(AbstractProductA&) : string
    }
}

' Family 2 - Concrete implementations
package "Product Family 2" {
    class ConcreteFactory2 {
        + createProductA() : AbstractProductA*
        + createProductB() : AbstractProductB*
    }
    
    class ConcreteProductA2 {
        + usefulFunctionA() : string
    }
    
    class ConcreteProductB2 {
        + usefulFunctionB() : string
        + anotherUsefulFunctionB(AbstractProductA&) : string
    }
}

' Inheritance relationships
AbstractFactory <|.. ConcreteFactory1
AbstractFactory <|.. ConcreteFactory2

AbstractProductA <|.. ConcreteProductA1
AbstractProductA <|.. ConcreteProductA2

AbstractProductB <|.. ConcreteProductB1
AbstractProductB <|.. ConcreteProductB2

' Factory creates products
AbstractFactory ..> AbstractProductA : creates
AbstractFactory ..> AbstractProductB : creates

ConcreteFactory1 .down.> ConcreteProductA1 : creates
ConcreteFactory1 .down.> ConcreteProductB1 : creates

ConcreteFactory2 .down.> ConcreteProductA2 : creates
ConcreteFactory2 .down.> ConcreteProductB2 : creates

note right of AbstractFactory
    Declares factory methods for
    creating abstract products
end note

@enduml
